"""arreglo tabla usuarios

Revision ID: 2e1ee09c57e5
Revises: d69cb662ee5f
Create Date: 2025-09-20 17:34:22.110239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1ee09c57e5'
down_revision: Union[str, Sequence[str], None] = 'd69cb662ee5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password_hash', sa.Text(), nullable=False))
    op.drop_constraint(op.f('usuarios_contraseña_hash_key'), 'usuarios', type_='unique')
    op.drop_column('usuarios', 'contraseña_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('contraseña_hash', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('usuarios_contraseña_hash_key'), 'usuarios', ['contraseña_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('usuarios', 'password_hash')
    # ### end Alembic commands ###
