"""checks y timestamps añadidos

Revision ID: 96b313efffda
Revises: 2e1ee09c57e5
Create Date: 2025-09-20 19:40:05.724682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b313efffda'
down_revision: Union[str, Sequence[str], None] = '2e1ee09c57e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('usuarios', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # Checks
    op.create_check_constraint(
        "chk_usuarios_email_minusculas", "usuarios", "email=lower(email)"
    )
    op.create_check_constraint(
        "chk_usuarios_usuario_minusculas", "usuarios", "usuario=lower(usuario)"
    )
    op.create_check_constraint(
        "chk_usuarios_edad", "usuarios", "edad BETWEEN 14 AND 90"
    )
    op.create_check_constraint(
        "chk_usuarios_peso", "usuarios", "peso BETWEEN 30 AND 200"
    )
    op.create_check_constraint(
        "chk_usuarios_altura", "usuarios", "altura BETWEEN 120 AND 220"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chk_usuarios_email_minusculas", "usuarios", type_="check")
    op.drop_constraint("chk_usuarios_usuario_minusculas", "usuarios", type_="check")
    op.drop_constraint("chk_usuarios_edad", "usuarios", type_="check")
    op.drop_constraint("chk_usuarios_peso", "usuarios", type_="check")
    op.drop_constraint("chk_usuarios_altura", "usuarios", type_="check")
    op.drop_column('usuarios', 'updated_at')
    op.drop_column('usuarios', 'created_at')
    # ### end Alembic commands ###
